// Better Auth setup (ADR 0011): e-mail + password, invite-only, database sessions, admin plugin.
import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { admin } from 'better-auth/plugins/admin';
import { adminAc, defaultAc, userAc } from 'better-auth/plugins/admin/access';
import { openAPI } from 'better-auth/plugins';
import type { Db } from '../db/client.js';
import { diver, diverManagement } from '../db/schema.js';
import { hashPassword, MAX_PASSWORD_LENGTH, MIN_PASSWORD_LENGTH, verifyPassword } from './password.js';

/**
 * The only Better Auth endpoints reachable over HTTP (ADR 0013). Everything else, including the admin
 * plugin's endpoints, sign-up and session listing (which returns session tokens), answers 404; admin
 * actions go through our own routes, which keep at least one admin and clean up stored files.
 */
export const PUBLIC_AUTH_PATHS = ['/sign-in/email', '/sign-out', '/get-session', '/change-password'] as const;

/** Fastify resolves the client IP (honouring DIVEHUB_TRUSTED_PROXIES) and hands it over in this header. */
export const CLIENT_IP_HEADER = 'x-divehub-client-ip';

export interface AuthOptions {
  db: Db;
  baseUrl: string;
  secret: string;
  /** Extra origins allowed to call the auth endpoints (the base URL's origin always is). */
  trustedOrigins?: string[];
  /** On by default in production; tests switch it on explicitly. */
  rateLimit?: boolean;
}

/**
 * Admins manage Users but can't impersonate them: signing in as someone would expose Dives whose
 * Visibility excludes the admin.
 */
const adminRole = defaultAc.newRole({
  ...adminAc.statements,
  user: adminAc.statements.user.filter((action) => action !== 'impersonate'),
});

export function createAuth({ db, baseUrl, secret, trustedOrigins = [], rateLimit }: AuthOptions) {
  return betterAuth({
    appName: 'Dive Hub',
    baseURL: baseUrl,
    basePath: '/api/auth',
    secret,
    trustedOrigins,
    database: drizzleAdapter(db, { provider: 'pg' }),
    telemetry: { enabled: false },
    emailAndPassword: {
      enabled: true,
      disableSignUp: true,
      minPasswordLength: MIN_PASSWORD_LENGTH,
      maxPasswordLength: MAX_PASSWORD_LENGTH,
      revokeSessionsOnPasswordReset: true,
      password: { hash: hashPassword, verify: verifyPassword },
    },
    session: {
      expiresIn: 60 * 60 * 24 * 7,
      updateAge: 60 * 60 * 24,
    },
    rateLimit: {
      ...(rateLimit !== undefined && { enabled: rateLimit }),
      storage: 'database',
      window: 60,
      max: 100,
      // Per client IP; about 10 attempts per 15 minutes on password sign-in.
      customRules: { '/sign-in/email': { window: 15 * 60, max: 10 } },
    },
    advanced: {
      // CSRF protection (Origin and Fetch Metadata checks) everywhere; Better Auth skips it in tests by default.
      disableOriginCheck: false,
      disableCSRFCheck: false,
      ipAddress: { ipAddressHeaders: [CLIENT_IP_HEADER] },
      // Our tables use uuid ids; Better Auth's are generated by the database too.
      database: { generateId: 'uuid' },
    },
    plugins: [
      admin({ roles: { admin: adminRole, user: userAc }, defaultRole: 'user' }),
      // Only for describing PUBLIC_AUTH_PATHS in our OpenAPI document; its own pages stay off.
      openAPI({ disableDefaultReference: true }),
    ],
    databaseHooks: {
      user: {
        create: {
          /** Every User gets their own Diver. */
          after: async (user) => {
            await db.transaction(async (tx) => {
              const [own] = await tx.insert(diver).values({ name: user.name }).returning({ id: diver.id });
              await tx.insert(diverManagement).values({ userId: user.id, diverId: own!.id, isOwn: true });
            });
          },
        },
      },
    },
  });
}

export type Auth = ReturnType<typeof createAuth>;
export type SessionUser = Auth['$Infer']['Session']['user'];
