/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Imports of the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: "pending" | "processing" | "done" | "failed";
                            uploadName: string;
                            /** Format: date-time */
                            createdAt: string;
                            finishedAt: string | null;
                            error: string | null;
                            outcome: {
                                fileName: string;
                                result: string;
                                diveId?: string;
                                recordingId?: string;
                                message?: string;
                            }[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Upload a FIT file or a zip archive (e.g. Garmin "Export Original") for import */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: "pending" | "processing" | "done" | "failed";
                            uploadName: string;
                            /** Format: date-time */
                            createdAt: string;
                            finishedAt: string | null;
                            error: string | null;
                            outcome: {
                                fileName: string;
                                result: string;
                                diveId?: string;
                                recordingId?: string;
                                message?: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Default Response */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One Import with its outcome */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: "pending" | "processing" | "done" | "failed";
                            uploadName: string;
                            /** Format: date-time */
                            createdAt: string;
                            finishedAt: string | null;
                            error: string | null;
                            outcome: {
                                fileName: string;
                                result: string;
                                diveId?: string;
                                recordingId?: string;
                                message?: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dives of the Divers the current user manages, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            number: number | null;
                            /** Format: date-time */
                            startsAt: string;
                            utcOffsetSeconds: number | null;
                            durationSeconds: number;
                            maxDepthM: number | null;
                            avgDepthM: number | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dives/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One Dive with its Recordings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            number: number | null;
                            /** Format: date-time */
                            startsAt: string;
                            utcOffsetSeconds: number | null;
                            durationSeconds: number;
                            maxDepthM: number | null;
                            avgDepthM: number | null;
                        } & {
                            recordings: {
                                id: string;
                                isPrimary: boolean;
                                /** Format: date-time */
                                startsAt: string;
                                durationSeconds: number;
                                maxDepthM: number | null;
                                parser: string;
                                summary: {
                                    [key: string]: unknown;
                                };
                                channels: string[];
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample series of a Recording, downsampled for display */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated channel names; default all */
                    channels?: string;
                    maxPoints?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recordingId: string;
                            series: {
                                channel: string;
                                offsetsMs: number[];
                                values: number[];
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
